a = input('Digite algo: ')
print(f'Qual o tipo primitivo? {type(a)}')
print(f'É um número? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'Está em MAIÚSCULAS? {a.isupper()}')
print(f'Está em minúsculas? {a.islower()}')
print(f'Está Captalizado? {a.istitle()}')
